[package]
name = "helloworld_tonic"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[[bin]] # Bin to run the HelloWorld gRPC server
name = "helloworld_server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "helloworld_client"
path = "src/client.rs"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
tonic-build = "0.11"
prost-types = { version = "0.12.6", default-features = false }
protoc-gen-prost ="0.3.1"
protoc-gen-tonic ="0.4.0"

[build-dependencies]
tonic-build = "0.11"
