[package]
name = "helloworld_tonic"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]] # Bin to run the HelloWorld gRPC server
name = "helloworld_server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "helloworld_client"
path = "src/client.rs"

[dependencies]
example_service = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
