[workspace]
resolver = "2"

members = [
    "rust/helloworld_tonic",
    "protos/example_service"
]

[workspace.package]
edition = "2021"
rust-version = "1.79.0"
readme = "README.md"


[workspace.dependencies]
example_service = { path = "protos/example_service" }
prost = { version = "0.12.6" }
prost-types = { version = "0.12.6", default-features = false }
tonic = { version = "0.11.0", features = ["transport"] }
tonic-build = "0.11.0"
tokio = { version = "1.38", default-features = false, features = ["macros", "net", "rt-multi-thread", "signal"] }
protoc-gen-tonic = "0.4.0"
protoc-gen-prost = "0.3.1"
