[package]
name = "doc_db"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[[bin]]
name = "doc_db"
path = "src/main.rs"

[dependencies]
dotenv = { workspace = true }
doc_db_proto = { workspace = true }
futures = { workspace = true }
mongodb = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }
