name: "Branch Build"

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: big_j

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: bazel-build-and-test
        run: |
          bazel build //... && bazel test //...
